# 系统
sys:
    kaptcha-open: false #是否开启登录时验证码 (true/false)
    kaptcha-length: 4 #验证码的长度
    # api接口模块，是通过jwt认证的，如果要使用api模块，则需要修改【加密秘钥】
    jwt:
        header: token
        # 加密秘钥
        secret: f4e2e52034348f86b67cde581c0f9eb5[vgk]
        # token有效时长，单位秒
        expire: 86400

# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-application-dev.ymlthreads: 1000
        min-spare-threads: 30
    port: 8894
    #打开注释，则通过【http://localhost:8894/vgk/admin】访问
    context-path: /sbed/admin

# mysql
spring:
    # 环境 dev|sit|uat|prod
    profiles:
        active: prod
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
                url: jdbc:mysql://localhost:3306/VGK?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: aa111111
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: localhost
        port: 6379
        password:       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml